[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 8888
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for Netlify functions
# Set these in your Netlify dashboard for production
# For local development, they're loaded from .env.local